[build]
  command = "pnpm install --frozen-lockfile && pnpm build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.18.1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client", "@prisma/engines"]
  included_files = [
    "node_modules/.prisma/client/**",
    "node_modules/@prisma/engines/**",
    "prisma/schema.prisma"
  ]